// Foto di <a href="https://pixabay.com/it/users/janjf93-3084263/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=2480165">janjf93</a> da <a href="https://pixabay.com/it/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=2480165">Pixabay</a>

/* XPM */
static const char *xpmImage[] = {
/* columns rows colors chars-per-pixel */
"64 64 156 2 ",
"   c #7CB57B",
".  c #DFF91F",
"X  c #EEFF0F",
"o  c #F7FF06",
"O  c #FAFF04",
"+  c #F3FF0C",
"@  c #F8FF08",
"#  c #E7FE17",
"$  c #EDFF13",
"%  c #E5FF1C",
"&  c #E8FF19",
"*  c #F0FF10",
"=  c #D1EF2C",
"-  c #D7F326",
";  c #DAF523",
":  c #DDF923",
">  c #D5F32B",
",  c #D9F72B",
"<  c #DAF828",
"1  c #C5E736",
"2  c #CAEB32",
"3  c #C2E53B",
"4  c #C5E83A",
"5  c #CAEE3B",
"6  c #CDF039",
"7  c #D2F332",
"8  c #E1FC21",
"9  c #86BB72",
"0  c #88BD70",
"q  c #9ECC5B",
"w  c #AAD44F",
"e  c #B4DA47",
"r  c #B9DF42",
"t  c #A2CF58",
"y  c #A6D153",
"u  c #A9D451",
"i  c #A9D75E",
"p  c #AEDE5D",
"a  c #B0DF5B",
"s  c #BCE140",
"d  c #BDE74C",
"f  c #BFE84A",
"g  c #B7E251",
"h  c #B8E351",
"j  c #8EC26D",
"k  c #97C861",
"l  c #9ACA62",
"z  c #8DC270",
"x  c #88C078",
"c  c #93CE7E",
"v  c #9DD571",
"b  c #96D17C",
"n  c #A6DA67",
"m  c #AADC62",
"M  c #A4D86A",
"N  c #C5EB42",
"B  c #1B7CEB",
"V  c #1075F6",
"C  c #147EFF",
"Z  c #72AE86",
"A  c #71AF8A",
"S  c #75B184",
"D  c #78B381",
"F  c #7EBA83",
"G  c #73B28B",
"H  c #7AB98C",
"J  c #62A69E",
"K  c #67AA99",
"L  c #74B490",
"P  c #78B890",
"I  c #79BE9C",
"U  c #569FA7",
"Y  c #589EA0",
"T  c #4A96B2",
"R  c #4E9CBA",
"E  c #519EB4",
"W  c #519FBA",
"Q  c #59A5AF",
"!  c #5EAAB1",
"~  c #62ACA9",
"^  c #69B6AF",
"/  c #6DB9AB",
"(  c #71B8A1",
")  c #66B4B4",
"_  c #68B4B0",
"`  c #61B1B9",
"'  c #7FC296",
"]  c #398ECA",
"[  c #3E93CA",
"{  c #2E8ADD",
"}  c #328AD4",
"|  c #328FDD",
" . c #2792DE",
".. c #2C94DE",
"X. c #3993D4",
"o. c #3197DF",
"O. c #3398DF",
"+. c #1A82FB",
"@. c #1A89FF",
"#. c #2482E3",
"$. c #2D8BE2",
"%. c #2586EB",
"&. c #2688ED",
"*. c #2B8DEB",
"=. c #2E96E0",
"-. c #2E91ED",
";. c #3399E0",
":. c #3E9EE2",
">. c #3395EC",
",. c #3699ED",
"<. c #399CEA",
"1. c #2286F5",
"2. c #268AF2",
"3. c #248EFE",
"4. c #2E94F5",
"5. c #2A92FB",
"6. c #3196F3",
"7. c #3499F2",
"8. c #3097F8",
"9. c #4596C0",
"0. c #489BC3",
"q. c #4FA4C8",
"w. c #55AAC7",
"e. c #51A7CD",
"r. c #53A9CB",
"t. c #4BA4D3",
"y. c #45A1DC",
"u. c #409FE2",
"i. c #42A1E4",
"p. c #4AA5E6",
"a. c #55AAE6",
"s. c #55ABE8",
"d. c #63B2EA",
"f. c #6BB6EB",
"g. c #6DB8EC",
"h. c #81BF88",
"j. c #85C387",
"k. c #8CC781",
"l. c #8DCA84",
"z. c #85C68F",
"x. c #89C98A",
"c. c #83C592",
"v. c #84C2EE",
"b. c #8DC7F1",
"n. c #92C9F0",
"m. c #99CDF2",
"M. c #ABD6F5",
"N. c #ABD7F5",
"B. c #B6DCF7",
"V. c #B8DDF7",
"C. c #C4E3F8",
"Z. c #CFE8FA",
"A. c #D0E8FA",
"S. c #E3F3FD",
"D. c #E4F3FD",
"F. c #FFFFFF",
/* pixels */
"F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.A.M.v.f.a.i.u.u.i.a.f.v.M.A.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.",
"F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.S.n.p. ...O.O.:.:.u.u.u.u.u.O.O.O.o. .p.n.S.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.",
"F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.M.i. .;.:.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.:.O...i.M.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.",
"F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.m...o.:.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.:.o.=.m.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.",
"F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.B.;.o.:.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.:.;.;.B.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.",
"F.F.F.F.F.F.F.F.F.F.F.F.F.F.a...:.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.:.:...a.F.F.F.F.F.F.F.F.F.F.F.F.F.F.",
"F.F.F.F.F.F.F.F.F.F.F.F.C...;.i.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.;...C.F.F.F.F.F.F.F.F.F.F.F.F.",
"F.F.F.F.F.F.F.F.F.F.F.b. .:.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u. .b.F.F.F.F.F.F.F.F.F.F.F.",
"F.F.F.F.F.F.F.F.F.F.f...u.u.u.u.u.u.u.u.u.u.u.u.u.:.u.u.:.u.:.:.:.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.i.O...f.F.F.F.F.F.F.F.F.F.F.",
"F.F.F.F.F.F.F.F.F.d.o.u.u.u.u.u.u.u.u.u.u.u.u.u.u.:.<.7.6.5.6.:.:.6.5.4.6.>.:.u.u.u.u.u.u.u.u.u.u.i.y.u.i.o.d.F.F.F.F.F.F.F.F.F.",
"F.F.F.F.F.F.F.F.f.o.u.u.u.u.u.u.u.u.u.u.u.u.u.<.4.u.c.m 7 + O o o O + > p c.u.4.,.:.u.u.u.u.u.u.u.u.u.u.u.u.o.f.F.F.F.F.F.F.F.F.",
"F.F.F.F.F.F.F.b...i.u.u.u.u.u.u.u.u.u.u.u.,.4.I 7 O + # & % & & & & % & # + O 6 I 4.,.u.u.u.u.u.u.u.u.u.u.u.u...b.F.F.F.F.F.F.F.",
"F.F.F.F.F.F.C. .O.u.u.u.u.u.u.u.u.u.u.<.5.c.* + # % % 8 & $ - 2 2 = + & % 8 % & + * z.5.<.u.u.u.u.u.u.u.u.u.u.:. .C.F.F.F.F.F.F.",
"F.F.F.F.F.F. .:.i.u.u.u.u.u.u.u.u.:.8.e.8 + % & + 8 % % X V *.*.*.*.C $ % % % + & & + : e.6.u.u.u.u.u.u.u.u.u.u.:. .F.F.F.F.F.F.",
"F.F.F.F.F.a.:.u.i.y.u.u.u.u.u.u.:.5.l.O & % + 2 Y [ + & r -.u.u.u.u.8.f # + [ ! 2 o % & O l.3.:.u.u.u.u.u.u.u.u.u.:.a.F.F.F.F.F.",
"F.F.F.F.B...u.u.u.u.u.u.u.u.u.u.5.g o % $ & Y %.8.c.* * j 7.u.u.u.u.,.c $ * F 8.5.! % $ & o g 5.u.u.u.u.u.u.u.u.u.:...B.F.F.F.F.",
"F.F.F.F.o.:.:.i.u.u.u.u.u.u.:.5.N * % @ y B :.i.7.n # * K <.u.u.u.i.,./ + $ t 7.u.<.5.i O % X N 5.:.u.u.u.u.u.u.u.u.u.o.F.F.F.F.",
"F.F.F.m.o.i.u.u.u.u.u.u.u.u.5.g $ % O Z %.u.u.u.4.5 # @ 9.:.u.u.u.i.:.t.o # 1 4.u.u.:.5.I O % X g 5.u.u.u.u.u.u.u.u.u.o.m.F.F.F.",
"F.F.F...O.u.u.u.u.u.u.u.u.6.l.o % O J >.u.u.u.u.5.# % O %.u.u.u.u.u.:.5.O % $ 2.u.u.u.u.4._ O % @ x 8.u.u.u.u.u.u.u.u.:...F.F.F.",
"F.F.M.o.i.u.u.u.u.u.u.u.<.r.O % @ Z *.u.u.u.u.u.,.O & - *.u.u.u.u.u.:.4., % O $.u.u.u.u.:.6.I O % O q.<.u.u.u.u.u.u.u.u.o.M.F.F.",
"F.F.i.:.y.u.u.u.u.u.u.u.5.8 & * y 2.u.u.u.u.u.<.w.+ # r -.u.u.u.u.u.u.6.f # o W <.u.u.u.u.u.5.m * % % 3.u.u.u.u.u.u.u.u.:.p.F.F.",
"F.D...u.i.u.u.u.u.u.u.>.c.+ % % B u.u.u.u.u.u.<./ + $ q >.u.u.u.u.u.u.7.M $ * K <.u.u.u.u.u.u.5.% % + h.,.u.u.u.u.u.u.u.O.o.D.F.",
"F.n.O.u.u.u.u.u.u.u.u.4.$ & @ Y <.u.u.u.u.u.u.<.c.$ $ 9 ,.i.:.:.u.:.:.,.x.$ + h.,.u.u.u.u.u.u.<.` @ % $ 2.i.i.u.u.u.u.u.i.O.n.F.",
"F.p.:.u.u.u.u.u.u.u.,.I + & 2 &.i.u.u.:.<.,.>.5.c $ + J 3.5.4.6.6.4.5.3.) + $ j 5.>.<.<.:.u.u.u.5.5 & + H ,.u.u.u.u.u.y.i.O.p.F.",
"F. .u.u.u.u.u.u.u.u.4.7 & + Y 8.7.4.5.t.) c.b m > % % & + O O o O O o o & % % > n c ' ) t.5.4.8.8.` + % 2 4.u.u.u.u.u.u.u.u. .F.",
"Z...u.u.u.u.u.u.u.:.O.O % % W b d < O o + * $ $ % % 8 % & & & & & & % & % % % % $ $ + + o o , h l.w.% % O X.:.u.u.u.u.u.u.u...A.",
"M.O.u.u.u.u.u.u.u.<.c.+ 8 % * * & & % & & * * + % % % * # : - > > - . & + % : & + * $ $ % % & & + + % % * H ,.i.u.u.u.u.u.u.O.M.",
"v.O.u.u.u.u.u.u.u.7.m $ % % & * + O # 3 y 0 G R 7 % O B &.*.*.*.*.*.*.%.+.o % > E G z y 1 # O + * $ % % $ u 6.u.u.u.u.u.u.u.;.v.",
"f.O.u.u.u.u.u.u.u.6.7 & & ; y   U { &.*.>.,.,.5.: & O %.i.i.u.u.u.u.u.u.4.O % ; 2.,.,.7.4.2.X.Q F u ; & % = *.u.u.u.u.u.u.u.:.f.",
"a.u.u.u.u.u.u.u.:.5.+ % + V >.,.<.:.u.u.u.u.u.4.% % @ %.i.u.u.u.u.u.u.u.5.o & % &.u.i.i.u.:.:.<.7.7.+.* % + 2.u.u.u.u.u.u.u.:.a.",
"p.u.u.u.u.u.u.u.:.6.O % > *.u.u.u.u.u.u.u.u.u.5.$ % + %.u.u.u.u.u.u.u.u.5.+ % # &.i.u.u.u.u.u.u.u.u.4.7 & O $.u.u.u.u.u.u.u.u.i.",
"u.u.u.u.u.u.u.u.:.:.@ & 2 *.u.u.u.u.u.u.u.u.u.5.$ & $ %.i.:.u.u.u.u.u.:.5.$ & X %.u.u.u.u.u.u.u.u.i.8.6 & O X.u.u.u.u.u.u.u.u.u.",
"u.u.u.u.u.u.u.u.:.u.O & 2 *.u.u.u.u.u.u.u.u.:.5.$ % * 2.u.u.u.u.u.u.u.u.5.$ & $ %.u.u.u.u.u.u.u.u.u.6.5 & @ X.<.i.u.u.u.u.u.u.u.",
"i.:.u.u.u.u.u.u.u.6.O % > *.u.u.u.u.u.u.u.u.u.4.# & + %.u.u.u.u.u.u.:.y.5.+ & # &.u.u.u.u.u.u.u.u.u.4., % O { :.u.u.u.u.u.u.u.i.",
"a.u.u.u.u.u.u.u.u.5.+ % * 1.4.8.>.:.:.u.:.u.u.4.& & O %.i.u.u.u.u.u.u.i.5.o & % *.u.u.:.u.:.<.,.6.4.3.* % + %.u.u.u.u.u.u.u.u.a.",
"f.O.u.u.u.u.u.u.u.4.7 & % O < a x.) u.5.8.8.7.3.< % O %.<.:.:.u.:.:.:.<.5.o % - 1.8.6.4.5.y.) x.a < O % & = *.u.u.u.u.u.u.y.O.f.",
"v.O.i.u.u.u.u.u.u.6.p $ 8 % & # $ + O o 7 f n c.> % o 0.y.<.,.6.6.,.:.y.t.o % > j.n N , o o + X # & 8 % & u >.u.u.u.u.u.u.u.;.v.",
"M.O.u.u.u.u.u.u.u.,.' * % % o * * & % % & $ $ $ % 8 8 + o @ O O O O o o + % % % $ $ % % % & $ $ + @ % % * D ,.u.u.u.u.u.u.u.O.M.",
"Z.;.u.u.u.u.u.u.u.:.u.O & ; %.~ 9 w 2 * O + + * & 8 % % & & & % & % & & % % % & * + + O # 2 y 9 ~ B : % O ] u.u.u.u.u.u.u.u.o.A.",
"F. .y.u.u.u.u.u.u.:.5.7 & + ~ 7.,.6.4.%.| E ~ L 4 & & 4 1 2 = = > = 2 3 3 & & s A J R | %.*.>.,.6.) o & 7 %.u.u.u.u.u.u.u.u. .F.",
"F.p.:.u.u.u.u.u.u.u.<.I + & 2 3.i.u.u.u.u.<.<.5.l.* + L 3.*.*.*.*.*.*.5.( X $ 0 8.<.<.u.i.u.u.u.5.5 & + S ,.u.u.u.u.u.u.u.:.p.F.",
"F.n.O.u.u.u.u.u.u.u.u.4.$ & o ! ,.u.u.u.u.u.i.,.I $ $ z 7.u.u.u.:.u.u.>.c $ * Z ,.u.u.u.u.u.u.<.` o % $ #.u.u.u.u.u.u.u.u.;.n.F.",
"F.D. .u.u.u.u.u.u.u.u.>.c.+ & # 4.u.u.u.u.u.u.<.) + # y 7.u.u.u.u.u.u.7.m $ + ~ <.u.u.u.u.u.:.5.% & +   >.u.u.u.u.u.u.u.u...D.F.",
"F.F.i.u.u.u.u.u.u.u.u.:.5.8 & $ i 5.u.u.u.u.u.:.t.o & 3 >.u.u.u.u.u.u.8.N # @ 9.u.u.u.u.u.u.5.m $ & % #.i.u.u.u.u.u.u.u.O.i.F.F.",
"F.F.M.o.u.u.u.u.u.u.u.u.<.e.O % O I 6.u.u.u.u.u.4.O % % 2.u.u.u.u.u.u.4.% % O #.i.u.u.u.u.8.I O % O T <.u.u.u.u.u.u.u.u.O.M.F.F.",
"F.F.F...O.u.u.u.u.u.u.u.u.8.l.o % O ^ 8.u.u.u.u.4.8 % O $.u.u.u.u.u.u.8.O % % %.u.u.u.u.8.^ O % + 0 -.u.u.u.u.u.u.u.u.:.;.F.F.F.",
"F.F.F.m.O.u.u.u.u.u.u.u.u.u.5.g X & O I 5.:.u.u.6.f & o W <.u.u.u.u.:.w.+ # s >.u.u.u.5.I O % * e %.u.u.u.u.u.u.u.u.u.o.m.F.F.F.",
"F.F.F.F.O.u.u.u.u.u.u.u.u.u.u.3.N X % O m 4.<.u.7.v $ * P ,.u.u.u.u.>.I + # k >.u.,.5.m O & * 3 B u.u.u.u.u.u.u.u.u.:.o.F.F.F.F.",
"F.F.F.F.B. .u.u.u.u.u.u.u.u.u.u.5.g @ & $ % ` 5.6.I X $ l 7.u.u.u.u.,.v $ * A 8.3.` % $ % o e #.i.u.u.u.u.u.u.u.u.u...B.F.F.F.F.",
"F.F.F.F.F.a.O.i.u.u.u.u.u.u.u.u.i.5.k.O & & o 5 ` <.o & 1 6.u.:.:.u.8.N & + } ` 5 @ # % @ 9 %.i.u.u.u.u.u.u.u.u.u.O.a.F.F.F.F.F.",
"F.F.F.F.F.F...:.u.u.u.u.u.u.u.u.i.O.7.q.. + % & + 8 % % o C 8.4.6.4.@.o % & 8 o # & + % T *.i.:.u.u.u.u.u.u.u.u.u...F.F.F.F.F.F.",
"F.F.F.F.F.F.C. .u.u.u.u.u.u.u.u.:.i.:.<.5.F $ + & % % 8 % * > 6 6 > * % 8 % % & + $   #.<.u.u.u.u.u.u.u.u.u.u.u. .C.F.F.F.F.F.F.",
"F.F.F.F.F.F.F.b...u.u.u.u.u.u.u.u.u.u.u.:.,.4.P 2 O + # & % % & & % % & & * O 2 S #.>.i.u.u.u.u.u.u.u.u.u.u.u...b.F.F.F.F.F.F.F.",
"F.F.F.F.F.F.F.F.f.O.u.u.u.u.u.u.u.u.u.u.u.:.:.<.4.X.H u = + @ o @ O + = u D ] *.,.u.u.i.u.u.u.u.u.u.u.u.u.u.o.g.F.F.F.F.F.F.F.F.",
"F.F.F.F.F.F.F.F.F.d.O.u.u.u.u.u.u.u.u.u.u.u.u.u.u.<.,.,.-.%.$.X.X.$.%.*.>.,.:.i.u.u.u.u.u.u.u.u.u.u.u.u.u.o.d.F.F.F.F.F.F.F.F.F.",
"F.F.F.F.F.F.F.F.F.F.f...u.u.u.u.u.u.u.u.u.u.u.u.u.u.i.i.u.i.:.i.:.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.o.g.F.F.F.F.F.F.F.F.F.F.",
"F.F.F.F.F.F.F.F.F.F.F.b. .O.i.i.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.i.:. .b.F.F.F.F.F.F.F.F.F.F.F.",
"F.F.F.F.F.F.F.F.F.F.F.F.C...;.y.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.O...C.F.F.F.F.F.F.F.F.F.F.F.F.",
"F.F.F.F.F.F.F.F.F.F.F.F.F.F.s.o.:.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.:...a.F.F.F.F.F.F.F.F.F.F.F.F.F.F.",
"F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.V.;.o.:.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.o.;.V.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.",
"F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.m.o.o.:.u.u.:.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.o...m.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.",
"F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.M.i. .O.:.u.u.u.u.u.u.u.u.u.u.u.u.u.u.u.:.:.;. .i.M.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.",
"F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.D.n.p.{ O.O.O.O.u.u.u.O.u.u.:.;.o.=. .p.n.D.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.",
"F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.A.M.v.f.a.i.u.y.p.a.f.v.M.A.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F."
};
